# Default application settings
[default]
app_name = "Generic API Framework"
version = "0.1.0"
debug = false

# Server settings
host = "0.0.0.0"
port = 8000

# API settings
api_prefix = "/api"
version_prefix = "/v1"

# Database settings - customize for your application
database_url = "postgresql+asyncpg://postgres:password@localhost:5432/your_app_db"
db_pool_size = 10
db_max_overflow = 20
db_pool_timeout = 30
db_pool_recycle = 3600

# Redis settings
redis_url = "redis://localhost:6379/0"
redis_max_connections = 10
redis_retry_on_timeout = true

# JWT settings - CHANGE THESE FOR YOUR APPLICATION
secret_key = "your-secret-key-change-this-immediately"
access_token_expire_minutes = 30
refresh_token_expire_days = 7
algorithm = "HS256"

# CORS settings
cors_origins = ["*"]
cors_allow_credentials = true
cors_allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH", "HEAD"]
cors_allow_headers = [
    "*",
    "Accept",
    "Accept-Language",
    "Content-Language",
    "Content-Type",
    "Authorization",
    "X-Requested-With",
    "X-API-Key",
    "X-Correlation-ID",
    "Origin",
    "Cache-Control",
    "Pragma"
]

# Logging settings
log_level = "INFO"
log_format = "json"

# Monitoring settings
metrics_enabled = true
metrics_path = "/metrics"
sentry_traces_sample_rate = 0.1
sentry_sample_rate = 0.1

# Observability settings
observability_log_requests = true
observability_log_responses = true
observability_log_request_body = false
observability_log_response_body = false
observability_mask_sensitive_data = true
observability_track_performance = true

# Structured logging settings
mask_sensitive_logs = true

# Rate limiting
rate_limit_enabled = true
rate_limit_requests = 100
rate_limit_window = 60

# Health checks
health_check_path = "/healthz"
readiness_check_path = "/readyz"
health_check_timeout = 5

# Performance settings
request_timeout = 30
max_request_size = 10485760  # 10MB
workers = 1
worker_class = "uvicorn.workers.UvicornWorker"
worker_connections = 1000

# Shutdown settings
shutdown_timeout = 30
shutdown_wait_for_connections = true
shutdown_force_after_timeout = true

# Feature flags - customize for your application
feature_example_enabled = true
# Add your own feature flags here

# Documentation settings
docs_enabled_in_production = false
docs_require_auth = true
docs_api_key = "change-this-docs-api-key"
docs_api_key_header = "X-Docs-API-Key"

# Swagger UI OAuth2 settings - configure if needed
swagger_oauth2_enabled = false
swagger_oauth2_client_id = "your-client-id"
swagger_oauth2_redirect_url = "/docs/oauth2-redirect"
