# Docker production environment settings
[default]
debug = false
reload = false
log_level = "WARNING"
log_format = "json"

# Docker production server settings
host = "0.0.0.0"
port = 8000

# Docker production monitoring
sentry_environment = "docker-production"
sentry_traces_sample_rate = 0.1
sentry_sample_rate = 0.1
metrics_enabled = true

# Docker production observability - minimal logging for performance
observability_log_requests = true
observability_log_responses = false  # Reduce logging in production
observability_log_request_body = false
observability_log_response_body = false
observability_mask_sensitive_data = true
observability_track_performance = true

# Docker production structured logging
mask_sensitive_logs = true

# Docker production features
feature_registration_enabled = true
feature_email_verification = true
feature_social_login = true

# Docker production performance - optimized for production load
workers = 4
worker_connections = 1000
request_timeout = 30
max_request_size = 5242880  # 5MB for production

# Docker production rate limiting - more restrictive
rate_limit_requests = 60
rate_limit_window = 60

# Docker production database pool - larger for production load
db_pool_size = 20
db_max_overflow = 40
db_pool_timeout = 30
db_pool_recycle = 3600

# Docker production health checks
health_check_timeout = 5
shutdown_timeout = 30

# Docker production security
cors_origins = []  # Should be configured via environment variables